#!/usr/bin/env node
const fs   = require('fs');
const path = require('path');

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};
  return Object.fromEntries(
    fs.readFileSync(filePath, 'utf8')
      .split('\n')
      .filter(line => line.trim() && !line.startsWith('#'))
      .map(line => {
        const [key, ...rest] = line.split('=');
        return [key.trim(), rest.join('=').trim()];
      })
  );
}

function write(env, outFile, production) {
  const apiUrl           = JSON.stringify(env['API_URL']             ?? '');
  const googleMapsApiKey = JSON.stringify(env['GOOGLE_MAPS_API_KEY'] ?? '');
  const content =
`// Generated by scripts/generate-env.js — do not edit by hand.
export const environment = {
  production: ${production},
  apiUrl: ${apiUrl},
  googleMapsApiKey: ${googleMapsApiKey},
};
`;
  fs.writeFileSync(outFile, content, 'utf8');
  console.log(`✅  ${path.basename(outFile)} written`);
}

const root        = path.resolve(__dirname, '..');
const isProd      = process.env['NODE_ENV'] === 'production';
const envFilePath = path.join(root, isProd ? '.env.production' : '.env');

// Merge: .env file takes precedence over process.env (allows Vercel env vars to work)
const fileEnv = parseEnvFile(envFilePath);
const env = {
  API_URL:             fileEnv['API_URL']             ?? process.env['API_URL']             ?? '',
  GOOGLE_MAPS_API_KEY: fileEnv['GOOGLE_MAPS_API_KEY'] ?? process.env['GOOGLE_MAPS_API_KEY'] ?? '',
};

const outFile = path.join(root, 'src/environments', isProd ? 'environment.prod.ts' : 'environment.ts');
write(env, outFile, isProd);
