#!/usr/bin/env node
/**
 * Reads frontend/.env (dev) and frontend/.env.production (prod) and writes
 * both environment.ts and environment.prod.ts.
 * Run automatically via the "prestart" and "prebuild" npm scripts.
 */
const fs = require('fs');
const path = require('path');

function parseEnv(filePath) {
  if (!fs.existsSync(filePath)) return null;
  return Object.fromEntries(
    fs.readFileSync(filePath, 'utf8')
      .split('\n')
      .filter(line => line.trim() && !line.startsWith('#'))
      .map(line => {
        const [key, ...rest] = line.split('=');
        return [key.trim(), rest.join('=').trim()];
      })
  );
}

function validate(env, file) {
  const required = ['API_URL', 'SUPABASE_URL', 'SUPABASE_ANON_KEY', 'GOOGLE_MAPS_API_KEY'];
  const missing = required.filter(k => !env[k]);
  if (missing.length) {
    console.error(`❌  Missing keys in ${file}: ${missing.join(', ')}`);
    process.exit(1);
  }
}

function write(env, outFile, production) {
  const content = `// AUTO-GENERATED by scripts/generate-env.js — do not edit by hand.
// Edit frontend/${production ? '.env.production' : '.env'} instead.
export const environment = {
  production: ${production},
  apiUrl: '${env['API_URL']}',
  supabaseUrl: '${env['SUPABASE_URL']}',
  supabaseAnonKey: '${env['SUPABASE_ANON_KEY']}',
  googleMapsApiKey: '${env['GOOGLE_MAPS_API_KEY']}',
};
`;
  fs.writeFileSync(outFile, content, 'utf8');
}

// --- Dev environment (required) ---
const devEnvPath  = path.resolve(__dirname, '../.env');
const devOutPath  = path.resolve(__dirname, '../src/environments/environment.ts');

if (!fs.existsSync(devEnvPath)) {
  console.error('❌  frontend/.env not found — copy .env.example and fill in your values.');
  process.exit(1);
}
const devEnv = parseEnv(devEnvPath);
validate(devEnv, '.env');
write(devEnv, devOutPath, false);
console.log('✅  environment.ts generated from frontend/.env');

// --- Production environment (optional — skipped if .env.production absent) ---
const prodEnvPath = path.resolve(__dirname, '../.env.production');
const prodOutPath = path.resolve(__dirname, '../src/environments/environment.prod.ts');

const prodEnv = parseEnv(prodEnvPath);
if (prodEnv) {
  validate(prodEnv, '.env.production');
  write(prodEnv, prodOutPath, true);
  console.log('✅  environment.prod.ts generated from frontend/.env.production');
} else {
  console.log('ℹ️   frontend/.env.production not found — environment.prod.ts not generated.');
}
