#!/usr/bin/env node
/**
 * Reads frontend/.env and writes src/environments/environment.ts.
 * Run automatically via the "prestart" and "prebuild" npm scripts.
 */
const fs = require('fs');
const path = require('path');

const envPath = path.resolve(__dirname, '../.env');
const outPath = path.resolve(__dirname, '../src/environments/environment.ts');

if (!fs.existsSync(envPath)) {
  console.error('❌  frontend/.env not found — copy .env.example and fill in your values.');
  process.exit(1);
}

// Parse .env manually (no extra dependency needed)
const env = Object.fromEntries(
  fs.readFileSync(envPath, 'utf8')
    .split('\n')
    .filter(line => line.trim() && !line.startsWith('#'))
    .map(line => {
      const [key, ...rest] = line.split('=');
      return [key.trim(), rest.join('=').trim()];
    })
);

const required = ['API_URL', 'SUPABASE_URL', 'SUPABASE_ANON_KEY', 'GOOGLE_MAPS_API_KEY'];
const missing = required.filter(k => !env[k]);
if (missing.length) {
  console.error(`❌  Missing required .env keys: ${missing.join(', ')}`);
  process.exit(1);
}

const content = `// AUTO-GENERATED by scripts/generate-env.js — do not edit by hand.
// Edit frontend/.env instead, then re-run \`npm start\` or \`npm run build\`.
export const environment = {
  production: false,
  apiUrl: '${env['API_URL']}',
  supabaseUrl: '${env['SUPABASE_URL']}',
  supabaseAnonKey: '${env['SUPABASE_ANON_KEY']}',
  googleMapsApiKey: '${env['GOOGLE_MAPS_API_KEY']}',
};
`;

fs.writeFileSync(outPath, content, 'utf8');
console.log('✅  environment.ts generated from frontend/.env');
