// AUTO-GENERATED by scripts/generate-env.js — do not edit by hand.
// Edit frontend/.env instead, then re-run `npm start` or `npm run build`.
export const environment = {
  production: false,
  apiUrl: 'http://localhost:3001',
  supabaseUrl: 'https://mfrwlfxhtvyzakycyksj.supabase.co',
  supabaseAnonKey: 'sb_publishable_-vrTA8ZJkPYPd3VWZw_RhA_oojw2f1T',
  googleMapsApiKey: 'YOUR_GOOGLE_MAPS_KEY',
};
