// Generated by scripts/generate-env.js — do not edit by hand.
export const environment = {
  production: false,
  apiUrl: "http://localhost:3001",
  googleMapsApiKey: "AIzaSyAS-Jswev22pd5tUP1agCgYFUwPUUUC7Z0",
};
